#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BOLD=`tput bold`
RED_BOLD=$BOLD`tput setaf 1`
GREEN_BOLD=$BOLD`tput setaf 2`
RESET=`tput sgr0`

if [[ $# != 1 ]]; then
	echo ${RED_BOLD}$0 requires exactly 1 argument.${RESET}
	echo Usage: $0 HW_NUMBER
	exit 1
fi

TO_DELETE=`ls "$DIR/bin/"`
if [[ $TO_DELETE != "" ]]; then
	echo ${RED_BOLD}DELETING${RESET}: $TO_DELETE

	# Give the user a moment to abort.
	sleep 1
	echo -n .
	sleep 1
	echo .
	sleep 1

	if rm -f "$DIR/bin/"*; then
		echo ${GREEN_BOLD}DELETED${RESET}
	else
		echo ${RED_BOLD}FAILURE${RESET}
		exit 1
	fi
fi

echo

INPUT_FILE=$DIR/hw${1}/hw${1}.tex
if ! [ -e "$INPUT_FILE" ]; then
	INPUT_FILE=$DIR/hw${1}.tex
fi

if ! [ -e "$INPUT_FILE" ]; then
	echo ${RED_BOLD}FAILURE${RESET}: Could not find suitable input file.
	exit 1
fi

pdflatex -interaction nonstopmode -output-directory bin "$INPUT_FILE"

if [[ $? == 0 ]]; then
	echo ${GREEN_BOLD}SUCCESS${RESET}
	evince "$DIR/bin/hw${1}.pdf" 2> /dev/null &
else
	echo ${RED_BOLD}FAILURE${RESET}: pdflatex failed.
fi
